# Generated by Django 2.0.2 on 2018-05-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hunter',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
